version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kompas_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kompas_db
      POSTGRES_USER: kompas_user
      POSTGRES_PASSWORD: kompas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kompas_net

  backend:
    build: .
    container_name: kompas_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kompas_db
      SPRING_DATASOURCE_USERNAME: kompas_user
      SPRING_DATASOURCE_PASSWORD: kompas_password
    depends_on:
      - db
    networks:
      - kompas_net

networks:
  kompas_net:

volumes:
  postgres_data: