spring:
  datasource:
    url: jdbc:postgresql://db:5432/kompas_db
    username: kompas_user
    password: kompas_password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog-master.yaml
debug: true